force-app/bedrock/lib/async/objects/Async__c/Async__c.object-meta.xml
<CustomObject>
    <label>Async</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Async Job #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/bedrock/lib/async/objects/Async__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Done</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/bedrock/lib/async/classes/AsyncTest.cls
@istest(testFor='ApexClass:Async')
public with sharing class AsyncTest {
    
    @istest static void testMock() {

        List<Contact> contacts = new List<Contact> {
            new Contact(LastName = 'Test1'),
            new Contact(LastName = 'Test2'),
            new Contact(LastName = 'Test3'),
            new Contact(LastName = 'Test4')
        };
        insert contacts;


        AsyncMock mock = new AsyncMock().canEnqueue();
        Async.setMock(mock);

        Test.startTest();
            Async.enqueue(MyTestAsync.class, contacts);
        Test.stopTest();

        for(Async__c workItem : [SELECT Id, Status__c FROM Async__c]) {
            System.assertEquals('Done', workItem.Status__c);
        }

        for(Contact contact : [SELECT Id, FirstName FROM Contact]) {
            System.assertEquals('Hello', contact.FirstName);
        }
    }

    public with sharing class MyTestAsync extends Async {
        public override void execute(Set<Id> ids) {
            List<Contact> contacts = [SELECT Id, FirstName, LastName FROM Contact WHERE Id IN :ids];
            for(Contact contact : contacts) {
                contact.FirstName = 'Hello';
            }
            update contacts;
        }
    }
}