force-app/bedrock/lib/async/objects/Async__c/Async__c.object-meta.xml
<CustomObject>
    <label>Async</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Async Job #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/bedrock/lib/async/objects/Async__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Done</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/bedrock/lib/async/classes/AsyncFilters.cls
/*
 * sf-bedrock: https://sfbedrock.com
 * Copyright 2026 Matthew Swing-McKenzie and Force Creators
 * SPDX-License-Identifier: MPL-2.0
 * License: https://mozilla.org/MPL/2.0/
 */

public with sharing class AsyncFilters {
    public static Boolean shouldRetry(
        List<Async__c> records,
        Map<Id, Async__c> oldMap
    ) {
        for (Async__c record : records) {
            if (
                record.Status__c == Async.consts.PENDING &&
                oldMap.get(record.Id).Status__c == Async.consts.ERROR
            ) {
                return true;
            }
        }
        return false;
    }
}